### ISSUE TITLE
Segmentation fault for lzfse encoded, lzvn compressed dmg files

### ISSUE THREAD

**Issue by ldeck** [matthewbauer/undmg#6]
I recently tried to update my macOS derivation for IntelliJ IDEA from 2020.1.4 to 2020.2, but undmg is failing for the 2020.2 dmg.

It appears Jetbrains has changed their dmgs with this new release.

Previously (which undmg worked fine for):
```
(version="2020.1.4"; curl -L -O "https://download.jetbrains.com/idea/ideaIU-${version}.dmg")
...
% file ideaIU-2020.1.4.dmg 
ideaIU-2020.1.4.dmg: zlib compressed data
```

Now (with lzfse/lzvn undmg segmentation faults):
```
% file /nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg
/nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg: lzfse encoded, lzvn compressed

% nix-env -i undmg
installing 'undmg-1.0.3'
building '/nix/store/i1a5ghk3dj6m4s48ya1zg642ljgwcgd2-user-environment.drv'...
created 927 symlinks in user environment
% reload
% mkdir /tmp/testdmg
% cd $_
% undmg < /nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg
zsh: segmentation fault  undmg < /nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg
```

Any suggestions?

See https://discourse.nixos.org/t/undmg-trouble-updating-custom-overlay-app-intellij-idea-2020-1-4-to-2020-2/8378

**Comment by matthewbauer** [comment]
I was able to extract it with undmg-1.0.4 (fixed in https://github.com/matthewbauer/undmg/commit/5595b5be015d4acd254f039be1a94ae34a01cd56). Could you try that?

**Comment by matthewbauer** [comment]
btw https://github.com/NixOS/nixpkgs/pull/94106 updates it in nixpkgs

**Comment by ldeck** [comment]
I added an overlay for undmg to use the 1.0.4 version

```
/nix/store/rbxyb97d3g1l23hz0dapm06m89fj1n4k-undmg-1.0.4/bin/undmg < /nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg
zsh: segmentation fault  /nix/store/rbxyb97d3g1l23hz0dapm06m89fj1n4k-undmg-1.0.4/bin/undmg < 
```

Perhaps I need to update nixpkgs also?

**Comment by ldeck** [comment]
@matthewbauer I’ve just updated nixpkgs and tried again. Still fails unfortunately.

```
% nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
"20.09pre236343.78215a8395f"
```

Hmm, seems like undmg-1.0.3 is still being used. Is 1.0.5 not published to nixpkgs-unstable yet?

```
 % nix-env -u IntelliJIDEA
upgrading 'IntelliJIDEA-2020.1.4' to 'IntelliJIDEA-2020.2'
these derivations will be built:
  /nix/store/sfl64n3mdzykwdk11wpdvfmj4qz8flxq-ideaIU-2020.2.dmg.drv
  /nix/store/7bw357k1kwj70ww9z6x37dhbp873p41i-IntelliJIDEA-2020.2.drv
these paths will be fetched (0.05 MiB download, 0.13 MiB unpacked):
  /nix/store/62hfjj84snrpq2pyqpzynd725yaq46f6-undmg-1.0.3
copying path '/nix/store/62hfjj84snrpq2pyqpzynd725yaq46f6-undmg-1.0.3' from 'https://cache.nixos.org'...
building '/nix/store/sfl64n3mdzykwdk11wpdvfmj4qz8flxq-ideaIU-2020.2.dmg.drv'...

trying https://download.jetbrains.com/idea/ideaIU-2020.2.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0    106      0  0:00:01  0:00:01 --:--:--   106
100  761M  100  761M    0     0  2644k      0  0:04:55  0:04:55 --:--:-- 2674k
building '/nix/store/7bw357k1kwj70ww9z6x37dhbp873p41i-IntelliJIDEA-2020.2.drv'...
unpacking sources
unpacking source archive /nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg
/nix/store/62hfjj84snrpq2pyqpzynd725yaq46f6-undmg-1.0.3/nix-support/setup-hook: line 2: 36552 Segmentation fault: 11  undmg < "$curSrc"
do not know how to unpack source archive /nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg
builder for '/nix/store/7bw357k1kwj70ww9z6x37dhbp873p41i-IntelliJIDEA-2020.2.drv' failed with exit code 1
error: build of '/nix/store/7bw357k1kwj70ww9z6x37dhbp873p41i-IntelliJIDEA-2020.2.drv' failed
```

So I’ve added an overlay to pull in the latest undmg:
```
self: super: {
undmg = super.undmg.overrideAttrs(oldAttrs: rec {
    version = "1.0.5";
    src = super.fetchFromGitHub {
      owner = "matthewbauer";
      repo = "undmg";
      rev = "v${version}";
      sha256 = "0yz5fniaa5z33d8bdzgr263957r1c9l99237y2p8k0hdid207la1";
    };
  });
}
```

But it still fails:
```
 % undmg < /nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg
Couldn't open extents tree
error: could not get volume
% file /nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg
/nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg: lzfse encoded, lzvn compressed
```

Any suggestions?

**Comment by matthewbauer** [comment]
Oh sorry - I was trying the first .dmg, not the second. Yes, it looks like this we need to add a dependency on lzfse: https://github.com/lzfse/lzfse.

**Comment by ldeck** [comment]
This might pose a challenge @matthewbauer, at least for users like me on macOS.

```
self: super: {
  undmg = super.undmg.overrideAttrs(oldAttrs: rec {
    version = "1.0.5";
    src = super.fetchFromGitHub {
      owner = "matthewbauer";
      repo = "undmg";
      rev = "v${version}";
      sha256 = "0yz5fniaa5z33d8bdzgr263957r1c9l99237y2p8k0hdid207la1";
    };
    buildInputs = with super.pkgs; [ zlib bzip2 lzfse ];
  });
}
```

lzfse not supported on darwin in nix at this time...
```
nix-env -i undmg
installing 'undmg-1.0.5'
error: Package ‘lzfse-2017-03-08’ in /nix/store/g2c2yky0nxjvqbfcr1ykx163gz7bm87r-nixpkgs-20.09pre236343.78215a8395f/nixpkgs/pkgs/tools/compression/lzfse/default.nix:20 is not supported on ‘x86_64-darwin’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.

```

**Comment by ldeck** [comment]
Hmm, so I overlayed the lzfse derivation to allow it to install on darwin @matthewbauer but still no success:
```
self: super: {
   undmg = super.undmg.overrideAttrs(oldAttrs: rec {
    version = "1.0.5";
    src = super.fetchFromGitHub {
      owner = "matthewbauer";
      repo = "undmg";
      rev = "v${version}";
      sha256 = "0yz5fniaa5z33d8bdzgr263957r1c9l99237y2p8k0hdid207la1";
    };
    buildInputs = with super.pkgs; [ zlib bzip2 lzfse ];
  });

  lzfse = super.lzfse.overrideAttrs(oldAttrs: rec {
    meta = oldAttrs.meta // {
      platforms = with super.stdenv.lib; platforms.all;
    };
  });
}
```

I can install undmg happily:
```
% nix-env -i undmg
installing 'undmg-1.0.5'
these derivations will be built:
  /nix/store/v80rwbd660vgngll74k61mx3b6zl64rg-lzfse-2017-03-08.drv
  /nix/store/zb10yqi57bizql370x07pfxi725krcbh-undmg-1.0.5.drv
these paths will be fetched (0.04 MiB download, 0.24 MiB unpacked):
  /nix/store/3mn4v5bv7ld4g663sr4kwpini492lry7-source
copying path '/nix/store/3mn4v5bv7ld4g663sr4kwpini492lry7-source' from 'https://cache.nixos.org'...
building '/nix/store/v80rwbd660vgngll74k61mx3b6zl64rg-lzfse-2017-03-08.drv'...
unpacking sources
unpacking source archive /nix/store/3mn4v5bv7ld4g663sr4kwpini492lry7-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
build flags: SHELL=/nix/store/lpqq5knklpr4v7s7nf2lzx6jx6615q6y-bash-4.4-p23/bin/bash INSTALL_PREFIX=\$\(out\)
clang -Os -Wall -Wno-unknown-pragmas -Wno-unused-variable -DNDEBUG -D_POSIX_C_SOURCE -std=c99 -fvisibility=hidden -c src/lzfse_encode.c -o build/obj/lzfse_encode.o
clang -Os -Wall -Wno-unknown-pragmas -Wno-unused-variable -DNDEBUG -D_POSIX_C_SOURCE -std=c99 -fvisibility=hidden -c src/lzfse_decode.c -o build/obj/lzfse_decode.o
clang -Os -Wall -Wno-unknown-pragmas -Wno-unused-variable -DNDEBUG -D_POSIX_C_SOURCE -std=c99 -fvisibility=hidden -c src/lzfse_encode_base.c -o build/obj/lzfse_encode_base.o
clang -Os -Wall -Wno-unknown-pragmas -Wno-unused-variable -DNDEBUG -D_POSIX_C_SOURCE -std=c99 -fvisibility=hidden -c src/lzfse_decode_base.c -o build/obj/lzfse_decode_base.o
clang -Os -Wall -Wno-unknown-pragmas -Wno-unused-variable -DNDEBUG -D_POSIX_C_SOURCE -std=c99 -fvisibility=hidden -c src/lzvn_encode_base.c -o build/obj/lzvn_encode_base.o
clang -Os -Wall -Wno-unknown-pragmas -Wno-unused-variable -DNDEBUG -D_POSIX_C_SOURCE -std=c99 -fvisibility=hidden -c src/lzvn_decode_base.c -o build/obj/lzvn_decode_base.o
clang -Os -Wall -Wno-unknown-pragmas -Wno-unused-variable -DNDEBUG -D_POSIX_C_SOURCE -std=c99 -fvisibility=hidden -c src/lzfse_fse.c -o build/obj/lzfse_fse.o
ld -r -o ./build/obj/liblzfse_master.o ./build/obj/lzfse_encode.o  ./build/obj/lzfse_decode.o ./build/obj/lzfse_encode_base.o ./build/obj/lzfse_decode_base.o ./build/obj/lzvn_encode_base.o ./build/obj/lzvn_decode_base.o ./build/obj/lzfse_fse.o
ar rvs build/bin/liblzfse.a ./build/obj/liblzfse_master.o
ar: creating archive build/bin/liblzfse.a
a - ./build/obj/liblzfse_master.o
clang -Os -Wall -Wno-unknown-pragmas -Wno-unused-variable -DNDEBUG -D_POSIX_C_SOURCE -std=c99 -fvisibility=hidden -c src/lzfse_main.c -o build/obj/lzfse_main.o
clang -Os -Wall -Wno-unknown-pragmas -Wno-unused-variable -DNDEBUG -D_POSIX_C_SOURCE -std=c99 -fvisibility=hidden -o build/bin/lzfse ./build/obj/lzfse_main.o ./build/bin/liblzfse.a
installing
install flags: SHELL=/nix/store/lpqq5knklpr4v7s7nf2lzx6jx6615q6y-bash-4.4-p23/bin/bash INSTALL_PREFIX=\$\(out\) install
install ./src/lzfse.h /nix/store/flq7gdxmx5qj843n4iy81m1hdh4yj2qs-lzfse-2017-03-08/include/lzfse.h
install ./build/bin/liblzfse.a /nix/store/flq7gdxmx5qj843n4iy81m1hdh4yj2qs-lzfse-2017-03-08/lib/liblzfse.a
install ./build/bin/lzfse /nix/store/flq7gdxmx5qj843n4iy81m1hdh4yj2qs-lzfse-2017-03-08/bin/lzfse
post-installation fixup
strip is /nix/store/r955jliy59lk4ccpy0fzhp100rahfxws-cctools-binutils-darwin-927.0.2/bin/strip
stripping (with command strip and flags -S) in /nix/store/flq7gdxmx5qj843n4iy81m1hdh4yj2qs-lzfse-2017-03-08/lib  /nix/store/flq7gdxmx5qj843n4iy81m1hdh4yj2qs-lzfse-2017-03-08/bin 
patching script interpreter paths in /nix/store/flq7gdxmx5qj843n4iy81m1hdh4yj2qs-lzfse-2017-03-08
building '/nix/store/zb10yqi57bizql370x07pfxi725krcbh-undmg-1.0.5.drv'...
unpacking sources
unpacking source archive /nix/store/121vg85b68d7dbydms3sd9bmb0k5h7d0-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
build flags: SHELL=/nix/store/lpqq5knklpr4v7s7nf2lzx6jx6615q6y-bash-4.4-p23/bin/bash PREFIX=\$\(out\)
cc -c  abstractfile.c -o abstractfile.o
cc -c  base64.c -o base64.o
cc -c  btree.c -o btree.o
cc -c  catalog.c -o catalog.o
cc -c  checksum.c -o checksum.o
cc -c  dmgfile.c -o dmgfile.o
cc -c  dmglib.c -o dmglib.o
cc -c  extents.c -o extents.o
cc -c  fastunicodecompare.c -o fastunicodecompare.o
cc -c  hfscompress.c -o hfscompress.o
cc -c  hfslib.c -o hfslib.o
cc -c  io.c -o io.o
cc -c  main.c -o main.o
cc -c  partition.c -o partition.o
cc -c  rawfile.c -o rawfile.o
cc -c  resources.c -o resources.o
cc -c  udif.c -o udif.o
cc -c  utility.c -o utility.o
cc -c  volume.c -o volume.o
cc -c  xattr.c -o xattr.o
cc  -lz -lc -lbz2 abstractfile.o base64.o btree.o catalog.o checksum.o dmgfile.o dmglib.o extents.o fastunicodecompare.o hfscompress.o hfslib.o io.o main.o partition.o rawfile.o resources.o udif.o utility.o volume.o xattr.o -o undmg
installing
install flags: SHELL=/nix/store/lpqq5knklpr4v7s7nf2lzx6jx6615q6y-bash-4.4-p23/bin/bash PREFIX=\$\(out\) install
mkdir -p /nix/store/v35cns15kxv7w0gxc45l49iw55nfr7r7-undmg-1.0.5/bin/
install undmg /nix/store/v35cns15kxv7w0gxc45l49iw55nfr7r7-undmg-1.0.5/bin/
post-installation fixup
strip is /nix/store/r955jliy59lk4ccpy0fzhp100rahfxws-cctools-binutils-darwin-927.0.2/bin/strip
stripping (with command strip and flags -S) in /nix/store/v35cns15kxv7w0gxc45l49iw55nfr7r7-undmg-1.0.5/bin 
patching script interpreter paths in /nix/store/v35cns15kxv7w0gxc45l49iw55nfr7r7-undmg-1.0.5
building '/nix/store/a56w7pckmr2knrmqxfngfj2rmnyy14ag-user-environment.drv'...
created 911 symlinks in user environment
```

But it still fails as before.
```
% /nix/store/v35cns15kxv7w0gxc45l49iw55nfr7r7-undmg-1.0.5/bin/undmg < /nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg
Couldn't open extents tree
error: could not get volume
```

**Comment by matthewbauer** [comment]
Oh sorry - I meant I need to implement that :)

Right now undmg just knows about bzip2 and zlib, but adding lzfse support should be straightforward.

**Comment by ldeck** [comment]
@matthewbauer okay, great. Are you looking to do that soon?

**Comment by ldeck** [comment]
HI @matthewbauer — any chance this might be included in 20.09 nixpkgs release or is this proving more challenging than you first thought?

**Comment by matthewbauer** [comment]
@ldeck Can you try out https://github.com/matthewbauer/undmg/commit/69ab407059aa57d4eadddb055722b0549a121e05? If that works for you, I can make a release + make a Nixpkgs PR.

**Comment by ldeck** [comment]
@matthewbauer thanks — I’ve tried, it fails for a different reason.

~/.config/nixpkgs/overlays/04-tools.nix
```
self: super: {
  undmg = super.undmg.overrideAttrs(oldAttrs: rec {
    version = "1.0.5.2";
    rev = "69ab407059aa57d4eadddb055722b0549a121e05";
    src = super.fetchFromGitHub {
      owner = "matthewbauer";
      repo = "undmg";
      # rev = "v${version}";
      rev = "${rev}";
      sha256 = "0yz5fniaa5z33d8bdzgr263957r1c9l99237y2p8k0hdid207la1";
    };
  });

  lzfse = super.lzfse.overrideAttrs(oldAttrs: rec {
    meta = oldAttrs.meta // {
      platforms = with super.stdenv.lib; platforms.all;
    };
  });
}
```

logs
```
% file /nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg
/nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg: lzfse encoded, lzvn compressed

% nix-env -u IntelliJIDEA
upgrading 'IntelliJIDEA-2020.1.4' to 'IntelliJIDEA-2020.2'
these derivations will be built:
  /nix/store/3h9sxni9jvs75f8y5f019givzq7mrk1q-undmg-1.0.5.2.drv
  /nix/store/vabacrxxh5lxcwg9fkwscdalx49yqhkj-IntelliJIDEA-2020.2.drv
building '/nix/store/3h9sxni9jvs75f8y5f019givzq7mrk1q-undmg-1.0.5.2.drv'...
unpacking sources
unpacking source archive /nix/store/121vg85b68d7dbydms3sd9bmb0k5h7d0-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
build flags: SHELL=/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash PREFIX=\$\(out\)
cc -c  abstractfile.c -o abstractfile.o
cc -c  base64.c -o base64.o
cc -c  btree.c -o btree.o
cc -c  catalog.c -o catalog.o
cc -c  checksum.c -o checksum.o
cc -c  dmgfile.c -o dmgfile.o
cc -c  dmglib.c -o dmglib.o
cc -c  extents.c -o extents.o
cc -c  fastunicodecompare.c -o fastunicodecompare.o
cc -c  hfscompress.c -o hfscompress.o
cc -c  hfslib.c -o hfslib.o
cc -c  io.c -o io.o
cc -c  main.c -o main.o
cc -c  partition.c -o partition.o
cc -c  rawfile.c -o rawfile.o
cc -c  resources.c -o resources.o
cc -c  udif.c -o udif.o
cc -c  utility.c -o utility.o
cc -c  volume.c -o volume.o
cc -c  xattr.c -o xattr.o
cc  -lz -lc -lbz2 abstractfile.o base64.o btree.o catalog.o checksum.o dmgfile.o dmglib.o extents.o fastunicodecompare.o hfscompress.o hfslib.o io.o main.o partition.o rawfile.o resources.o udif.o utility.o volume.o xattr.o -o undmg
installing
install flags: SHELL=/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash PREFIX=\$\(out\) install
mkdir -p /nix/store/da7hp4jgyqwzynl7fhivc866sj5bq4wd-undmg-1.0.5.2/bin/
install undmg /nix/store/da7hp4jgyqwzynl7fhivc866sj5bq4wd-undmg-1.0.5.2/bin/
post-installation fixup
strip is /nix/store/4jhsnmp85b2y30cwyg3xzyffdzzbqasz-cctools-binutils-darwin-927.0.2/bin/strip
stripping (with command strip and flags -S) in /nix/store/da7hp4jgyqwzynl7fhivc866sj5bq4wd-undmg-1.0.5.2/bin 
patching script interpreter paths in /nix/store/da7hp4jgyqwzynl7fhivc866sj5bq4wd-undmg-1.0.5.2
building '/nix/store/vabacrxxh5lxcwg9fkwscdalx49yqhkj-IntelliJIDEA-2020.2.drv'...
unpacking sources
unpacking source archive /nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg
Couldn't open extents tree
error: could not get volume
do not know how to unpack source archive /nix/store/xm545xvkbl41ng2bcgd5kg5rb0lsk1s0-ideaIU-2020.2.dmg
builder for '/nix/store/vabacrxxh5lxcwg9fkwscdalx49yqhkj-IntelliJIDEA-2020.2.drv' failed with exit code 1
error: build of '/nix/store/vabacrxxh5lxcwg9fkwscdalx49yqhkj-IntelliJIDEA-2020.2.drv' failed
```

**Comment by matthewbauer** [comment]
I think the hash is wrong. Try substituting 0yz5fniaa5z33d8bdzgr263957r1c9l99237y2p8k0hdid207la1 with 0000000000000000000000000000000000000000000000000000.

**Comment by ldeck** [comment]
Ah yes, I forgot to update the hash... okay, next issue...

Do I need to override the buildinputs?

```
 % nix-prefetch-github --rev 69ab407059aa57d4eadddb055722b0549a121e05 matthewbauer undmg
{
    "owner": "matthewbauer",
    "repo": "undmg",
    "rev": "69ab407059aa57d4eadddb055722b0549a121e05",
    "sha256": "0aq4bag7adl6bd4cqgpck6mdzpycywahbb78rvb2kvmwa99sydr2",
    "fetchSubmodules": false
}%                                                                                                                                                                                                                                            ldeck@LDeck undmgtest % nix-env -u IntelliJIDEA                                                          
upgrading 'IntelliJIDEA-2020.1.4' to 'IntelliJIDEA-2020.2'
these derivations will be built:
  /nix/store/ik5zpjlyibr55il1mj96lp3q84w2h5a6-undmg-1.0.5.2.drv
  /nix/store/hx6xc8zca2nbay2jlfhnjxsrvknz0n0l-IntelliJIDEA-2020.2.drv
building '/nix/store/ik5zpjlyibr55il1mj96lp3q84w2h5a6-undmg-1.0.5.2.drv'...
unpacking sources
unpacking source archive /nix/store/16x4lwnvcs5xc4fmvwiwcqjb11592ik0-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
build flags: SHELL=/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash PREFIX=\$\(out\)
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   abstractfile.c -o abstractfile.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   base64.c -o base64.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   btree.c -o btree.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   catalog.c -o catalog.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   checksum.c -o checksum.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   dmgfile.c -o dmgfile.o
dmgfile.c:10:10: fatal error: 'lzfse.h' file not found
#include <lzfse.h>
         ^~~~~~~~~
1 error generated.
make: *** [Makefile:28: dmgfile.o] Error 1
builder for '/nix/store/ik5zpjlyibr55il1mj96lp3q84w2h5a6-undmg-1.0.5.2.drv' failed with exit code 2
cannot build derivation '/nix/store/hx6xc8zca2nbay2jlfhnjxsrvknz0n0l-IntelliJIDEA-2020.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/hx6xc8zca2nbay2jlfhnjxsrvknz0n0l-IntelliJIDEA-2020.2.drv' failed
```

**Comment by ldeck** [comment]
I added the following `buildInputs = with super.pkgs; [ zlib bzip2 lzfse ];` and re-ran

```
 % nix-env -u IntelliJIDEA
upgrading 'IntelliJIDEA-2020.1.4' to 'IntelliJIDEA-2020.2'
these derivations will be built:
  /nix/store/7g0kmnjhi73slxfc51b3fxdi96zsflmi-undmg-1.0.5.2.drv
  /nix/store/yxngyi53jjq91pjdxnk9b0hivvbvdias-IntelliJIDEA-2020.2.drv
building '/nix/store/7g0kmnjhi73slxfc51b3fxdi96zsflmi-undmg-1.0.5.2.drv'...
unpacking sources
unpacking source archive /nix/store/16x4lwnvcs5xc4fmvwiwcqjb11592ik0-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
build flags: SHELL=/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash PREFIX=\$\(out\)
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   abstractfile.c -o abstractfile.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   base64.c -o base64.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   btree.c -o btree.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   catalog.c -o catalog.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   checksum.c -o checksum.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   dmgfile.c -o dmgfile.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   dmglib.c -o dmglib.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   extents.c -o extents.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   fastunicodecompare.c -o fastunicodecompare.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   hfscompress.c -o hfscompress.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   hfslib.c -o hfslib.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   io.c -o io.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   main.c -o main.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   partition.c -o partition.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   rawfile.c -o rawfile.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   resources.c -o resources.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   udif.c -o udif.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   utility.c -o utility.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   volume.c -o volume.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
clang -c   xattr.c -o xattr.o
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
/nix/store/saggdc3mgg1h6fs05r9rv5isypqwzby8-bash-4.4-p23/bin/bash: pkg-config: command not found
ld    -llzfse -lc abstractfile.o base64.o btree.o catalog.o checksum.o dmgfile.o dmglib.o extents.o fastunicodecompare.o hfscompress.o hfslib.o io.o main.o partition.o rawfile.o resources.o udif.o utility.o volume.o xattr.o -o undmg
Undefined symbols for architecture x86_64:
  "_BZ2_bzDecompress", referenced from:
      _cacheOffset in dmgfile.o
      _extractBLKX in io.o
  "_BZ2_bzDecompressEnd", referenced from:
      _cacheOffset in dmgfile.o
      _extractBLKX in io.o
  "_BZ2_bzDecompressInit", referenced from:
      _cacheOffset in dmgfile.o
      _extractBLKX in io.o
  "_compress", referenced from:
      _closeHFSPlusCompressed in hfscompress.o
  "_deflate", referenced from:
      _insertBLKX in io.o
  "_deflateEnd", referenced from:
      _insertBLKX in io.o
  "_deflateInit_", referenced from:
      _insertBLKX in io.o
  "_inflate", referenced from:
      _cacheOffset in dmgfile.o
      _extractBLKX in io.o
  "_inflateEnd", referenced from:
      _cacheOffset in dmgfile.o
      _extractBLKX in io.o
  "_inflateInit_", referenced from:
      _cacheOffset in dmgfile.o
      _extractBLKX in io.o
  "_uncompress", referenced from:
      _openHFSPlusCompressed in hfscompress.o
      _compressedRead in hfscompress.o
ld: symbol(s) not found for inferred architecture x86_64
make: *** [Makefile:18: undmg] Error 1
builder for '/nix/store/7g0kmnjhi73slxfc51b3fxdi96zsflmi-undmg-1.0.5.2.drv' failed with exit code 2
cannot build derivation '/nix/store/yxngyi53jjq91pjdxnk9b0hivvbvdias-IntelliJIDEA-2020.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/yxngyi53jjq91pjdxnk9b0hivvbvdias-IntelliJIDEA-2020.2.drv' failed
```

**Comment by matthewbauer** [comment]
Actually it's easier to just try undmg from  `nixos-unstable`.

**Comment by ldeck** [comment]
> Actually it's easier to just try undmg from `nixos-unstable`.

Okay, cool. I’ve successfully updated to IntelliJIDEA-2020.2.1. Thanks!

**Comment by matthewbauer** [comment]
Awesome!
